//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Framework.ApplicationDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResearchDBEntities : DbContext
    {
        public ResearchDBEntities()
            : base("name=ResearchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<branchs> branchs { get; set; }
        public virtual DbSet<facultys> facultys { get; set; }
        public virtual DbSet<master_process> master_process { get; set; }
        public virtual DbSet<process_document> process_document { get; set; }
        public virtual DbSet<research_groups> research_groups { get; set; }
        public virtual DbSet<research_process> research_process { get; set; }
        public virtual DbSet<researches> researches { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<teachers> teachers { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
