//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Research_Framework.ApplicationDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class process_document
    {
        public int id { get; set; }
        public int research_process_id { get; set; }
        public string document_type { get; set; }
        public string file_path { get; set; }
        public System.DateTime upload_date { get; set; }
        public int upload_by { get; set; }
        public string document_status { get; set; }
    }
}
